Customization of iOS audio categories from flutter.
llfbandit/record pull request #396
Opened 2024-09-05 09:59 UTC by chanonly123

iOS specific only.
Now we can send this in `RecordConfig`, `iosAudioCategories`. 
```
const config = RecordConfig(encoder: encoder, numChannels: 1, iosAudioCategories: [IosAudioCategories.allowBluetoothA2DP]);
```
When recording starts, iOS recorder uses these categories.

2024-09-05 10:43 UTC, llfbandit requested changes

2024-09-05 10:43 UTC, llfbandit commented on record/example/lib/audio_recorder.dart
> +        const config = RecordConfig(encoder: encoder, numChannels: 1, iosAudioCategories: [IosAudioCategories.allowBluetoothA2DP]);
Please let it with default values.

2024-09-05 10:43 UTC, llfbandit commented on record_platform_interface/lib/src/types/record_config.dart
> +  final List<IosAudioCategories> iosAudioCategories;
We should wrap those iOS specific categories in `iosConfig` of type `IosRecordConfig`.

2024-09-05 10:43 UTC, llfbandit commented on record_platform_interface/lib/src/types/record_config.dart
> +    this.iosAudioCategories = const [IosAudioCategories.defaultToSpeaker, IosAudioCategories.allowBluetooth, IosAudioCategories.allowBluetoothA2DP],
👍

2024-09-05 10:43 UTC, llfbandit commented on record_darwin/ios/Classes/RecorderIOS.swift
> +    } ?? []
Should we re-apply previous default values?

2024-09-05 10:44 UTC, llfbandit commented
Thanks for your contribution!
Despite few changes requested, everything looks good! 👍

2024-09-05 11:21 UTC, llfbandit commented on record_darwin/ios/Classes/RecorderIOS.swift
> +    } ?? []
No that's fine as categories will never be nil.

2024-09-05 12:22 UTC, chanonly123 commented
Mapping from `String` to `AVAudioSession.CategoryOptions` enums moved. Please check.

2024-09-05 12:33 UTC, llfbandit commented on record_darwin/darwin/Classes/RecordConfig.swift
> +  func toMap() -> [String: Any] {
`toMap` can be removed, it is never called. Or am I missing something?

2024-09-05 12:48 UTC, llfbandit approved these changes

2024-09-05 12:49 UTC, merged

2024-09-05 12:50 UTC, llfbandit commented
Many thanks for first opening ios specific config!

2024-09-05 12:53 UTC, chanonly123 commented
Welcome. 
BTW tried to run macos project but `pod install` breaking. Can you help me here, then I can update for macos as well.
I am using `melos bootstrap` inside root.

2024-09-05 13:10 UTC, llfbandit commented
In the example project?
What if you delete macos/Podfile.lock?

Also be sure to use a not too old version of cocoapod.

2024-09-30 10:47 UTC, tgalery commented
I am also having some issues using the code incorporated in this MR:

I've added the following on my pubspec dependencies.

```
 record:
    git:
      url: https://github.com/llfbandit/record.git
      ref: master
      path: record
```

Looking at the pubspec.lock things seem to be updated to the `5.1.3` version and the `record_darwin` version to `1.1.2`. However the `record_platform_interface` seems to be unchanged and essentially this doesn't allow me to use the ios config.

Would it be possible to make a new release available to the general public with the changes ?

Thanks a lot !

2024-10-01 15:11 UTC, tgalery commented
@chanonly123 could you specify the steps to use the code in this git repo to test locally ? My local env is resolving to hosted versions which do not contain the changes you introduce in this MR.

2024-10-02 07:28 UTC, chanonly123 commented
just run command `melos bootstrap`