Allow recording through bluetooth headsets on iOS
llfbandit/record pull request #5
Opened 2021-02-22 10:03 UTC by peret

I noticed that when using a bluetooth headsets on iOS, starting the recording will choose an audio route that doesn't use the headset at all. Bluetooth has to be explicitly allowed on the audio session for this to work. I think on Android, it just works.

Since for my use case I definitely want to record through the headset when one is connected, I created this fix for myself. I think this might be useful for others as well, so would you consider merging this into the project? If you're not keen on always enabling bluetooth, I could also add another option to control this behavior.

2021-02-22 10:47 UTC, llfbandit commented
Hi,

Thanks for your work 👍 
The changes are fine (not tested). Just change your var to let for options.

Need to check the behaviour on Android platform. Maybe, setting audio source to `DEFAULT` could do it. For now, this is set to `MIC` explicitly.
But I don't have bluetooth device to check it, can you ?

I definitly want to keep both platforms on par.

2021-02-25 16:59 UTC, bdremynoel requested changes

2021-02-25 16:59 UTC, bdremynoel commented on ios/Classes/SwiftRecordPlugin.swift
> +      if #available(iOS 10.0, *) {
This is output-only profile. It should be removed.

2021-03-04 15:37 UTC, llfbandit commented
Added without allowBluetoothA2DP profile

2021-03-04 15:37 UTC, closed without merging